import {PostActions} from "./ProblemAction";
import {AnyAction} from "redux";
import State, {initialState} from '../../Redux/State';

/**
 * the reducer for redux to handle all the updates comming from ProblemActions generated by Problempage
 * @param state the current state of the application
 * @param action the action that has been performed
 * @author Wouter Grootjans
 */
export default function (state : State = initialState, action : AnyAction) : State{
    switch(action.type) {
        case PostActions.PROBLEM_FETCH_START:
            return {...state, loading: true, isProblemFetched: false, errorMessage: ""}
        case PostActions.PROBLEM_FETCH_SUCCESS:
            return {
                ...state, 
                loading: false, 
                isProblemFetched: true, 
                problems: action.payload,
                errorMessage: ''}
        case PostActions.PROBLEM_FETCH_FAIL:
            return {...state, loading: false, isProblemFetched: false, errorMessage: action.payload}
        default:
            return state
    }
}