# Never use latest, always a version
FROM node:13.10

# The destination of our app in the container
WORKDIR /usr/src/app

# Moves the package.json and tsconfig.json to the specified workdir
COPY package.json ./
COPY tsconfig.json ./

# Connect with remote database
ENV NODE_ENV 'production'
ENV POSTGRES_URI 'postgres://rezxbigrwzzblk:a52e3c719233b8923ebbe871efa653faa497725a23aec3a813aefb96d6406dac@ec2-54-247-94-127.eu-west-1.compute.amazonaws.com:5432/d7vifc4lf4qkfg'
ENV TZ = 'Europe/Brussels'

RUN npm install

COPY . .

CMD ["npm", "start"]