# Never use latest, always a version
FROM node:13.10

# The destination of our app in the container
WORKDIR /usr/src/app

# Moves the package.json and tsconfig.json to the specified workdir
COPY package.json ./
COPY tsconfig.json ./

# Create user and postgres
ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD 12345
ENV POSTGRES_DB postgres
ENV POSTGRES_URI 'postgres://postgres:12345@database-debug:5432/postgres'

# Connect with nginx
ENV PORT 3001

RUN npm install

COPY . .


CMD ["npm", "start"]