FROM node:13.10

# The destination of our app in the container
WORKDIR /usr/src/app

# Copy react app to the container
COPY package.json ./
COPY tsconfig.json ./
COPY ionic.config.json ./

# Prepare the container for building react
RUN npm install

ENV NODE_ENV "development"

# Fire up
CMD ["npm", "start"]