# Never use latest, always a version
FROM node:13.10

# The destination of our app in the container
WORKDIR /usr/src/app

# Copy react app to the container
COPY package.json ./
COPY tsconfig.json ./

# Prepare the container for building react
RUN npm install

# Fire up
CMD ["npm", "start"]