# Never use latest, always a version
FROM node:13.10 as builder

# The destination of our app in the container
WORKDIR /usr/src/app

# Copy react app to the container
COPY package.json ./
COPY tsconfig.json ./

# Prepare the container for building react
RUN npm install

COPY . .

RUN npm run build

# Prepare nginx
FROM nginx:1.17.9

COPY --from=builder /usr/src/app/build /usr/share/nginx/html