import {PDFActions} from "./PDFActions";
import {AnyAction} from "redux";
import State, {initialState} from '../../Redux/State';

/**
 * the reducer for redux to handle all the updates comming from PDFActions generated by GeneratePDFButton
 * @param state the current state of the application
 * @param action the action that has been performed
 */
export default function (state : State = initialState, action : AnyAction) : State{
    switch(action.type) {
        case PDFActions.PDF_FETCH_START:
            return {...state, loading: true, errorMessage: ""}
        case PDFActions.PDF_FETCH_SUCCES:
            return {
                ...state, 
                loading: false, 
                errorMessage: ''}
        case PDFActions.PDF_FETCH_FAIL:
            return {...state, loading: false, errorMessage: action.payload}
        default:
            return state
    }
}