import {MapActions} from './MapAction';
import {AnyAction} from "redux";
import State, {initialState} from '../../Redux/State';

/**
 * the reducer for redux to handle all the updates comming from MapActions generated by MapPage
 * @param state the current state of the application
 * @param action the action that has been performed
 */
export default function (state : State = initialState, action : AnyAction) : State {
    switch(action.type) {
        case MapActions.MAP_FETCH_START:
            return {...state, loading: true, isMapFetched: false, errorMessage: ""}
        case MapActions.MAP_FETCH_SUCCES:
            return {...state, 
                    loading: false, 
                    isMapFetched: true,
                    users: action.payload.users,
                    problems: action.payload.problems,
                    posts: action.payload.posts, 
                    errorMessage: ""}
        case MapActions.MAP_FETCH_FAIL:
            return {...state, loading: false, isMapFetched: false, errorMessage: action.payload}
        default:
            return state
    }
}